name: truyencuatui
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0



environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  bottom_picker: ^2.4.0
  cupertino_icons: ^1.0.2
  en_vi_dic: ^1.0.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  http: ^1.2.0
  percent_indicator: ^4.2.3
  riverpod_annotation: ^2.3.5
  flutter_otp_text_field: ^1.1.0+2
  fl_chart: ^0.66.2
  intl: ^0.17.0
  collection: ^1.15.0
  shared_preferences: ^2.0.8
  get_it: ^7.2.0
  flutter_spinkit: "^5.1.0"
  

dev_dependencies:
  build_runner: ^2.4.8
  custom_lint: ^0.6.4
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  
  carousel_slider: ^4.0.0
  riverpod_generator: ^2.4.0
  image_picker: ^0.8.6

flutter:
  uses-material-design: true

  assets:
    - images/background.jpg 
    - images/truyen99.jpeg
    - images/Background.png 
    - images/Background1.png 
    - images/logo.png
    - images/logo1.png
    - images/Color.jpg 
    - images/mystery.jpg
    - images/romance.jpg
    - images/scifi.jpg
    - images/adventure.jpg
    - images/drama.jpg 
    - images/truyen06.jpg
    - images/truyen05.jpg 
    - images/truyencuatui.png # Thêm dòng này để liệt kê tệp tài nguyên
    - assets/json/




  
